spring.application.name=week07-lab
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:week07-lab}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration-access=${JWT_EXPIRATION_ACCESS:3600000}

app.booking.email-dir=${BOOKING_EMAIL_DIR:emails}
